org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
systemProp.file.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.230
loader_version_range=[1,)

mod_id=tradesquares
mod_name=TradeSquares
mod_license=MIT
mod_version=0.1.0
mod_group_id=net.tradesquares
